### ISSUE TITLE
Schema Generation For Waypoints Function Failing

### ISSUE THREAD

**Issue by es-markjbyrne** [ShadowTraffic/requests#4]
When attempting to use the waypoints generator with a kafka connection I am getting the following error.

```
Exception in thread "main" clojure.lang.ExceptionInfo: Can't yet automatically create schema for function waypoints {}
```

This may be user error but the way I am reading it it seems like its a current limitation of the waypoints generator itself?

**Comment by MichaelDrogalis** [comment]
Hey @es-markjbyrne, your reading is right: it's a short-term limitation of the product. It doesn't yet know how to automatically generate a schema for this kind of data.

Some good news, though: I've been iterating on this function a lot, and now I'm done, so I can get this fixed in one of the next releases. I'll keep this thread posted.

**Comment by MichaelDrogalis** [comment]
By the way, if you still want ShadowTraffic to still be responsible for creating the schema, you can hint it, either for [Avro](https://docs.shadowtraffic.io/generator-configuration/kafkaValueAvroSchemaHint/) or [Postgres](https://docs.shadowtraffic.io/function-modifiers/pgHint/).

**Comment by MichaelDrogalis** [comment]
I found a few free minutes and knocked this out.

Try `0.4.12` ([changelog](https://docs.shadowtraffic.io/changelog/#0412)). For Postgres, it generates a `JSON` type. For Avro, a `record`. For JSON Schema, an `object`.
