### ISSUE TITLE
Please add support for generating protocol buffer messages 

### ISSUE THREAD

**Issue by ilanKeshet** [ShadowTraffic/requests#5]
Hi ShadowTraffic! 
We don't really send JSON over Kafka. We only send messages in [Protocol buffers](https://protobuf.dev/) binary wire format 

### An imaginary flow of how this could work
1. The user would provide a reference to `.proto` file as part of the json config
2. ShadowTraffic will read the file, understand the contents and the Message types inside it
3. ShadowTraffic would generate data as specified and covert the `value` to the protocol buffer Message specified before sending it on the wire

### An imaginary example 
Based on https://github.com/ShadowTraffic/shadowtraffic-examples/blob/master/inventory-queries.json 
```json 
{
    "generators": [
        {
            "topic": "transaction.input.topic",
			"serialization": {
				"proto3": "my.protobuf.message.Transaction"
			} ,
            "value": {
                "transactionId": {
                    "_gen": "sequentialInteger"
                },
                "ts": {
                    "_gen": "now"
                },
                "itemId": {
                    "_gen": "sequentialString",
                    "expr": "item_~d"
                },
                "quantity": {
                    "_gen": "uniformDistribution",
                    "bounds": [1, 5],
                    "decimals": 0
                }
            },
            "localConfigs": {
                "throttleMs": {
                    "_gen": "normalDistribution",
                    "mean": 200,
                    "sd": 50
                }
            }
        },
        {
            "topic": "query.input.topic",
			"serialization":{
				"proto3": "my.protobuf.message.Query"
			} ,
            "value": {
                "queryId": {
                    "_gen": "sequentialInteger"
                },
                "ts": {
                    "_gen": "now"
                },
                "itemId": {
                    "_gen": "lookup",
                    "topic": "transaction.input.topic",
                    "path": [ "value", "itemId" ]
                }
            },
            "localConfigs": {
                "throttleMs": 500
            }
        }
    ],
    "serializations": {
       "proto3": {
            "files": ["./path/to/my/protobuf/message/filename.proto"],
            "messages": [
				"my.protobuf.message.MyMessage",
				"my.protobuf.message.Transaction",
				"my.protobuf.message.Query",
			]
        }
	}
    "connections": {
        "dev-kafka": {
            "kind": "kafka",
            "producerConfigs": {
                "bootstrap.servers": "localhost:9092",
                "key.serializer": "io.shadowtraffic.kafka.serdes.ProtoSerializer",
                "value.serializer": "io.shadowtraffic.kafka.serdes.ProtoSerializer"
            }
        }
    }
}
```

*️⃣ A future addition to only support direct reference of `.proto` files, would be to support a connection to a schema registry. (Personally, I'd rather have file support).

**Comment by MichaelDrogalis** [comment]
Thanks for your suggestion! This makes a ton of sense. Give me a couple of days and I'll turn it around. :-)

**Comment by ilanKeshet** [comment]
@MichaelDrogalis Thank you

**Comment by MichaelDrogalis** [comment]
Just to keep you posted: I have a sketch of this done and expect it to get it out early next week, probably on Monday.

**Comment by ilanKeshet** [comment]
Amazing!

**Comment by MichaelDrogalis** [comment]
Protobuf file supported has been released in 0.8.6:

- Mount your Protobuf files into your ShadowTraffic container, the same way you do with your configuration (`-v ...`)
- Set the [`kafkaKeyProtobufHint`](https://docs.shadowtraffic.io/generator-configuration/kafkaKeyProtobufHint/) local configuration if you want to serialize the key, supplying the schema file and message type.
- Ditto [`kafkaValueProtobufHint`](https://docs.shadowtraffic.io/generator-configuration/kafkaValueProtobufHint/) for the value.

In all, your configuration should look something like this:

```json
{
    "generators": [
        {
            "topic": "sandbox",
            "value": {
                "x": {
                    "_gen": "boolean"
                }
            },
            "localConfigs": {
                "kafkaValueProtobufHint": {
                    "schemaFile": "/container/path/to/schema.proto",
                    "message": "MyMessage"
                }
            }
        }
    ],
    "connections": {
        "kafka": {
            "kind": "kafka",
            "producerConfigs": {
                "bootstrap.servers": "localhost:9092",
                "schema.registry.url": "http://localhost:8081",
                "key.serializer": "io.shadowtraffic.kafka.serdes.JsonSerializer",
                "value.serializer": "io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer"
            }
        }
    }
}
```

Let me know if you have any questions! 😀

**Comment by ilanKeshet** [comment]
Hi @MichaelDrogalis , Wow, that was fast ⚡⚡  

**Questions:** 
1. May I assume that protobuf [well known types](https://protobuf.dev/reference/protobuf/google.protobuf/) are automatically present in the path?  
2. May I assume that if my `.proto` file references another `.proto` file, it'll be loaded if placed in an appropriate relative path? 
3. Can a protobuf message be serialized as a headers value? 
4. Is message nesting supported?

**Comment by MichaelDrogalis** [comment]
@ilanKeshet Ah, good questions! I'm rather unfamiliar with Protobuf, so let me just describe how it works under the covers, and perhaps you'll uncover the answers to your questions:

1. When ShadowTraffic starts up and sees that you want to use Protobuf, it loads the file at the path described in `kafkaKey/ValueProtobufHint`.
2. It takes that file and constructs a [ProtobufSchema](https://github.com/confluentinc/schema-registry/blob/master/protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema.java) object. This is a utility class provided by Schema Registry. The object is constructed with the loaded schema, no references, no resolved references, version hard-coded to `1`, and the name of the message type you want to use.
3. When an event is sent, it's serialized with [ProtobufSchemaUtils](https://github.com/confluentinc/schema-registry/blob/master/protobuf-provider/src/main/java/io/confluent/kafka/schemaregistry/protobuf/ProtobufSchemaUtils.java) `toObject` method.

So I think the answers to your questions are:
1. Yes.
2. No, because only one file is loaded.
3. No, [headers are expected to be UTF-8 strings](https://docs.shadowtraffic.io/connections/kafka/#setting-record-headers). I can extend this to add further serializations, though. It was just an easy first step when adding headers.
4. Yes, based on some cursory testing.

Feel free to send back any suggestions, since like I said, I'm a protobuf n00b. :)
